with base(category,question_type,prompt,options) as (values
('Classic Preferences','preference','What would {player_name} choose as a dream gift?','["A surprise trip","The latest tech","Something handmade","A shopping spree"]'::jsonb),
('Classic Preferences','preference','What is {player_name}''s ideal way to recharge?','["A long nap","Time outdoors","A movie marathon","Meeting friends"]'::jsonb),
('Classic Preferences','preference','Which treat would {player_name} save for last?','["Chocolate cake","Spicy snacks","Ice cream","Fresh fruit"]'::jsonb),
('Classic Preferences','preference','Which view would {player_name} wake up to?','["Ocean waves","Mountain peaks","City lights","A quiet garden"]'::jsonb),
('Situational Questions','situation','If {player_name} won a free flight tonight, where would they go?','["A tropical island","A famous city","A mountain town","Wherever friends choose"]'::jsonb),
('Situational Questions','situation','If the power went out all evening, what would {player_name} do?','["Tell stories","Go for a walk","Sleep early","Find a board game"]'::jsonb),
('Situational Questions','situation','What would {player_name} rescue first from a very messy room?','["Their phone","A favorite outfit","Important documents","The snacks"]'::jsonb),
('Situational Questions','situation','If {player_name} became famous tomorrow, what would it be for?','["A creative talent","A brave idea","A funny moment","Helping people"]'::jsonb),
('Funny & Chaotic','hypothetical','Which harmless supervillain plan suits {player_name}?','["Ban early alarms","Replace rain with confetti","Make snacks free","Declare every Friday a holiday"]'::jsonb),
('Funny & Chaotic','hypothetical','Which animal would {player_name} trust as a personal assistant?','["A clever crow","A loyal dog","A calm capybara","A dramatic cat"]'::jsonb),
('Funny & Chaotic','hypothetical','What would {player_name} do first during a fake apocalypse?','["Raid the snack aisle","Build a blanket fort","Take a selfie","Create a team plan"]'::jsonb),
('Funny & Chaotic','hypothetical','Which weird contest could {player_name} secretly win?','["Fastest nap","Best excuse","Loudest laugh","Most tabs open"]'::jsonb),
('This or That','this_or_that','What would {player_name} pick for a spontaneous weekend?','["Road trip","Staycation","Festival","Nature escape"]'::jsonb),
('This or That','this_or_that','Which everyday luxury matters more to {player_name}?','["Fast Wi-Fi","Great coffee","Soft pillows","Zero traffic"]'::jsonb),
('This or That','this_or_that','Which power would {player_name} rather have?','["Teleportation","Mind reading","Time pause","Perfect memory"]'::jsonb),
('This or That','this_or_that','What schedule would {player_name} choose?','["Early bird","Night owl","Four-day week","No schedule at all"]'::jsonb),
('Friends','personality','What makes {player_name} feel most appreciated by friends?','["A thoughtful message","Quality time","Practical help","A surprise plan"]'::jsonb),
('Friends','personality','What role does {player_name} play in a group trip?','["The planner","The navigator","The entertainer","The snack manager"]'::jsonb),
('Friends','personality','What would {player_name} remember from a great party?','["The conversations","The music","The food","One hilarious moment"]'::jsonb),
('Friends','situation','How would {player_name} cheer up a friend?','["Listen quietly","Send memes","Plan an outing","Bring food"]'::jsonb),
('Couples','preference','Which date would {player_name} enjoy most?','["Cozy dinner","Adventure activity","Live show","Sunset walk"]'::jsonb),
('Couples','preference','Which small gesture would charm {player_name}?','["A favorite snack","A handwritten note","A planned surprise","A perfect playlist"]'::jsonb),
('Family','situation','What is {player_name} most likely to bring to a family gathering?','["A signature dish","A game","Family gossip","A last-minute excuse"]'::jsonb),
('Family','situation','Which family tradition would {player_name} happily lead?','["Holiday cooking","Photo day","Game night","Travel planning"]'::jsonb),
('Office','personality','What is {player_name} secretly best at during meetings?','["Finding solutions","Reading the room","Taking clear notes","Keeping everyone awake"]'::jsonb),
('Office','preference','Which desk upgrade would {player_name} choose?','["A standing desk","A coffee machine","A giant monitor","A cozy chair"]'::jsonb),
('Office','situation','How would {player_name} celebrate finishing a huge project?','["Team dinner","A day off","Quiet satisfaction","An elaborate victory dance"]'::jsonb),
('Office','personality','Which work message describes {player_name}?','["Already done","Quick question","Let''s simplify","Coffee first"]'::jsonb),
('Mixed','hypothetical','What would {player_name} buy first if money were no object?','["A dream home","A world tour","A luxury car","A creative studio"]'::jsonb),
('Mixed','personality','Which word best describes {player_name} on a good day?','["Curious","Reliable","Playful","Ambitious"]'::jsonb)
), twists(suffix) as (values(''),(' — decide instantly.'),(' — no overthinking.'),(' when nobody is judging?'))
insert into public.questions(category,question_type,prompt,options,is_curated,enabled)
select category,question_type,prompt||suffix,options,true,true from base cross join twists;
